
export const timezones = [
    { value: "Africa/Abidjan", label: "(UTC+00:00) Abidjan" },
    { value: "Africa/Accra", label: "(UTC+00:00) Accra" },
    { value: "Africa/Algiers", label: "(UTC+01:00) Algiers" },
    { value: "Africa/Bissau", label: "(UTC+00:00) Bissau" },
    { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
    { value: "Africa/Casablanca", label: "(UTC+01:00) Casablanca" },
    { value: "Africa/Ceuta", label: "(UTC+01:00) Ceuta" },
    { value: "Africa/El_Aaiun", label: "(UTC+01:00) El Aaiun" },
    { value: "Africa/Johannesburg", label: "(UTC+02:00) Johannesburg" },
    { value: "Africa/Juba", label: "(UTC+02:00) Juba" },
    { value: "Africa/Khartoum", label: "(UTC+02:00) Khartoum" },
    { value: "Africa/Lagos", label: "(UTC+01:00) Lagos" },
    { value: "Africa/Maputo", label: "(UTC+02:00) Maputo" },
    { value: "Africa/Monrovia", label: "(UTC+00:00) Monrovia" },
    { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
    { value: "Africa/Ndjamena", label: "(UTC+01:00) Ndjamena" },
    { value: "Africa/Sao_Tome", label: "(UTC+01:00) Sao Tome" },
    { value: "Africa/Tripoli", label: "(UTC+02:00) Tripoli" },
    { value: "Africa/Tunis", label: "(UTC+01:00) Tunis" },
    { value: "Africa/Windhoek", label: "(UTC+02:00) Windhoek" },
    { value: "America/Adak", label: "(UTC-10:00) Adak" },
    { value: "America/Anchorage", label: "(UTC-09:00) Anchorage" },
    { value: "America/Araguaina", label: "(UTC-03:00) Araguaina" },
    { value: "America/Argentina/Buenos_Aires", label: "(UTC-03:00) Buenos Aires" },
    { value: "America/Argentina/Catamarca", label: "(UTC-03:00) Catamarca" },
    { value: "America/Argentina/Cordoba", label: "(UTC-03:00) Cordoba" },
    { value: "America/Argentina/Jujuy", label: "(UTC-03:00) Jujuy" },
    { value: "America/Argentina/La_Rioja", label: "(UTC-03:00) La Rioja" },
    { value: "America/Argentina/Mendoza", label: "(UTC-03:00) Mendoza" },
    { value: "America/Argentina/Rio_Gallegos", label: "(UTC-03:00) Rio Gallegos" },
    { value: "America/Argentina/Salta", label: "(UTC-03:00) Salta" },
    { value: "America/Argentina/San_Juan", label: "(UTC-03:00) San Juan" },
    { value: "America/Argentina/San_Luis", label: "(UTC-03:00) San Luis" },
    { value: "America/Argentina/Tucuman", label: "(UTC-03:00) Tucuman" },
    { value: "America/Argentina/Ushuaia", label: "(UTC-03:00) Ushuaia" },
    { value: "America/Asuncion", label: "(UTC-04:00) Asuncion" },
    { value: "America/Atikokan", label: "(UTC-05:00) Atikokan" },
    { value: "America/Bahia", label: "(UTC-03:00) Bahia" },
    { value: "America/Bahia_Banderas", label: "(UTC-06:00) Bahia Banderas" },
    { value: "America/Barbados", label: "(UTC-04:00) Barbados" },
    { value: "America/Belem", label: "(UTC-03:00) Belem" },
    { value: "America/Belize", label: "(UTC-06:00) Belize" },
    { value: "America/Blanc-Sablon", label: "(UTC-04:00) Blanc-Sablon" },
    { value: "America/Boa_Vista", label: "(UTC-04:00) Boa Vista" },
    { value: "America/Bogota", label: "(UTC-05:00) Bogota" },
    { value: "America/Boise", label: "(UTC-07:00) Boise" },
    { value: "America/Cambridge_Bay", label: "(UTC-07:00) Cambridge Bay" },
    { value: "America/Campo_Grande", label: "(UTC-04:00) Campo Grande" },
    { value: "America/Cancun", label: "(UTC-05:00) Cancun" },
    { value: "America/Caracas", label: "(UTC-04:00) Caracas" },
    { value: "America/Cayenne", label: "(UTC-03:00) Cayenne" },
    { value: "America/Chicago", label: "(UTC-06:00) Chicago" },
    { value: "America/Chihuahua", label: "(UTC-07:00) Chihuahua" },
    { value: "America/Costa_Rica", label: "(UTC-06:00) Costa Rica" },
    { value: "America/Creston", label: "(UTC-07:00) Creston" },
    { value: "America/Cuiaba", label: "(UTC-04:00) Cuiaba" },
    { value: "America/Curacao", label: "(UTC-04:00) Curacao" },
    { value: "America/Danmarkshavn", label: "(UTC+00:00) Danmarkshavn" },
    { value: "America/Dawson", label: "(UTC-07:00) Dawson" },
    { value: "America/Dawson_Creek", label: "(UTC-07:00) Dawson Creek" },
    { value: "America/Denver", label: "(UTC-07:00) Denver" },
    { value: "America/Detroit", label: "(UTC-05:00) Detroit" },
    { value: "America/Edmonton", label: "(UTC-07:00) Edmonton" },
    { value: "America/Eirunepe", label: "(UTC-05:00) Eirunepe" },
    { value: "America/El_Salvador", label: "(UTC-06:00) El Salvador" },
    { value: "America/Fort_Nelson", label: "(UTC-07:00) Fort Nelson" },
    { value: "America/Fortaleza", label: "(UTC-03:00) Fortaleza" },
    { value: "America/Glace_Bay", label: "(UTC-04:00) Glace Bay" },
    { value: "America/Goose_Bay", label: "(UTC-04:00) Goose Bay" },
    { value: "America/Grand_Turk", label: "(UTC-05:00) Grand Turk" },
    { value: "America/Guatemala", label: "(UTC-06:00) Guatemala" },
    { value: "America/Guayaquil", label: "(UTC-05:00) Guayaquil" },
    { value: "America/Guyana", label: "(UTC-04:00) Guyana" },
    { value: "America/Halifax", label: "(UTC-04:00) Halifax" },
    { value: "America/Havana", label: "(UTC-05:00) Havana" },
    { value: "America/Hermosillo", label: "(UTC-07:00) Hermosillo" },
    { value: "America/Indiana/Indianapolis", label: "(UTC-05:00) Indianapolis" },
    { value: "America/Indiana/Knox", label: "(UTC-06:00) Knox" },
    { value: "America/Indiana/Marengo", label: "(UTC-05:00) Marengo" },
    { value: "America/Indiana/Petersburg", label: "(UTC-05:00) Petersburg" },
    { value: "America/Indiana/Tell_City", label: "(UTC-06:00) Tell City" },
    { value: "America/Indiana/Vevay", label: "(UTC-05:00) Vevay" },
    { value: "America/Indiana/Vincennes", label: "(UTC-05:00) Vincennes" },
    { value: "America/Indiana/Winamac", label: "(UTC-05:00) Winamac" },
    { value: "America/Inuvik", label: "(UTC-07:00) Inuvik" },
    { value: "America/Iqaluit", label: "(UTC-05:00) Iqaluit" },
    { value: "America/Jamaica", label: "(UTC-05:00) Jamaica" },
    { value: "America/Juneau", label: "(UTC-09:00) Juneau" },
    { value: "America/Kentucky/Louisville", label: "(UTC-05:00) Louisville" },
    { value: "America/Kentucky/Monticello", label: "(UTC-05:00) Monticello" },
    { value: "America/La_Paz", label: "(UTC-04:00) La Paz" },
    { value: "America/Lima", label: "(UTC-05:00) Lima" },
    { value: "America/Los_Angeles", label: "(UTC-08:00) Los Angeles" },
    { value: "America/Maceio", label: "(UTC-03:00) Maceio" },
    { value: "America/Managua", label: "(UTC-06:00) Managua" },
    { value: "America/Manaus", label: "(UTC-04:00) Manaus" },
    { value: "America/Martinique", label: "(UTC-04:00) Martinique" },
    { value: "America/Matamoros", label: "(UTC-06:00) Matamoros" },
    { value: "America/Mazatlan", label: "(UTC-07:00) Mazatlan" },
    { value: "America/Menominee", label: "(UTC-06:00) Menominee" },
    { value: "America/Merida", label: "(UTC-06:00) Merida" },
    { value: "America/Metlakatla", label: "(UTC-09:00) Metlakatla" },
    { value: "America/Mexico_City", label: "(UTC-06:00) Mexico City" },
    { value: "America/Miquelon", label: "(UTC-03:00) Miquelon" },
    { value: "America/Moncton", label: "(UTC-04:00) Moncton" },
    { value: "America/Monterrey", label: "(UTC-06:00) Monterrey" },
    { value: "America/Montevideo", label: "(UTC-03:00) Montevideo" },
    { value: "America/Nassau", label: "(UTC-05:00) Nassau" },
    { value: "America/New_York", label: "(UTC-05:00) New York" },
    { value: "America/Nipigon", label: "(UTC-05:00) Nipigon" },
    { value: "America/Nome", label: "(UTC-09:00) Nome" },
    { value: "America/Noronha", label: "(UTC-02:00) Noronha" },
    { value: "America/North_Dakota/Beulah", label: "(UTC-06:00) Beulah" },
    { value: "America/North_Dakota/Center", label: "(UTC-06:00) Center" },
    { value: "America/North_Dakota/New_Salem", label: "(UTC-06:00) New Salem" },
    { value: "America/Nuuk", label: "(UTC-03:00) Nuuk" },
    { value: "America/Ojinaga", label: "(UTC-07:00) Ojinaga" },
    { value: "America/Panama", label: "(UTC-05:00) Panama" },
    { value: "America/Pangnirtung", label: "(UTC-05:00) Pangnirtung" },
    { value: "America/Paramaribo", label: "(UTC-03:00) Paramaribo" },
    { value: "America/Phoenix", label: "(UTC-07:00) Phoenix" },
    { value: "America/Port-au-Prince", label: "(UTC-05:00) Port-au-Prince" },
    { value: "America/Port_of_Spain", label: "(UTC-04:00) Port of Spain" },
    { value: "America/Porto_Velho", label: "(UTC-04:00) Porto Velho" },
    { value: "America/Puerto_Rico", label: "(UTC-04:00) Puerto Rico" },
    { value: "America/Punta_Arenas", label: "(UTC-03:00) Punta Arenas" },
    { value: "America/Rainy_River", label: "(UTC-06:00) Rainy River" },
    { value: "America/Rankin_Inlet", label: "(UTC-06:00) Rankin Inlet" },
    { value: "America/Recife", label: "(UTC-03:00) Recife" },
    { value: "America/Regina", label: "(UTC-06:00) Regina" },
    { value: "America/Resolute", label: "(UTC-06:00) Resolute" },
    { value: "America/Rio_Branco", label: "(UTC-05:00) Rio Branco" },
    { value: "America/Santarem", label: "(UTC-03:00) Santarem" },
    { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
    { value: "America/Santo_Domingo", label: "(UTC-04:00) Santo Domingo" },
    { value: "America/Sao_Paulo", label: "(UTC-03:00) Sao Paulo" },
    { value: "America/Scoresbysund", label: "(UTC-01:00) Scoresbysund" },
    { value: "America/Sitka", label: "(UTC-09:00) Sitka" },
    { value: "America/St_Johns", label: "(UTC-03:30) St. Johns" },
    { value: "America/Swift_Current", label: "(UTC-06:00) Swift Current" },
    { value: "America/Tegucigalpa", label: "(UTC-06:00) Tegucigalpa" },
    { value: "America/Thule", label: "(UTC-04:00) Thule" },
    { value: "America/Thunder_Bay", label: "(UTC-05:00) Thunder Bay" },
    { value: "America/Tijuana", label: "(UTC-08:00) Tijuana" },
    { value: "America/Toronto", label: "(UTC-05:00) Toronto" },
    { value: "America/Vancouver", label: "(UTC-08:00) Vancouver" },
    { value: "America/Whitehorse", label: "(UTC-07:00) Whitehorse" },
    { value: "America/Winnipeg", label: "(UTC-06:00) Winnipeg" },
    { value: "America/Yakutat", label: "(UTC-09:00) Yakutat" },
    { value: "America/Yellowknife", label: "(UTC-07:00) Yellowknife" },
    { value: "Antarctica/Casey", label: "(UTC+11:00) Casey" },
    { value: "Antarctica/Davis", label: "(UTC+07:00) Davis" },
    { value: "Antarctica/DumontDUrville", label: "(UTC+10:00) DumontDUrville" },
    { value: "Antarctica/Macquarie", label: "(UTC+10:00) Macquarie" },
    { value: "Antarctica/Mawson", label: "(UTC+05:00) Mawson" },
    { value: "Antarctica/Palmer", label: "(UTC-03:00) Palmer" },
    { value: "Antarctica/Rothera", label: "(UTC-03:00) Rothera" },
    { value: "Antarctica/Syowa", label: "(UTC+03:00) Syowa" },
    { value: "Antarctica/Troll", label: "(UTC+00:00) Troll" },
    { value: "Antarctica/Vostok", label: "(UTC+06:00) Vostok" },
    { value: "Asia/Almaty", label: "(UTC+05:00) Almaty" },
    { value: "Asia/Amman", label: "(UTC+03:00) Amman" },
    { value: "Asia/Anadyr", label: "(UTC+12:00) Anadyr" },
    { value: "Asia/Aqtau", label: "(UTC+05:00) Aqtau" },
    { value: "Asia/Aqtobe", label: "(UTC+05:00) Aqtobe" },
    { value: "Asia/Ashgabat", label: "(UTC+05:00) Ashgabat" },
    { value: "Asia/Atyrau", label: "(UTC+05:00) Atyrau" },
    { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
    { value: "Asia/Baku", label: "(UTC+04:00) Baku" },
    { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok" },
    { value: "Asia/Barnaul", label: "(UTC+07:00) Barnaul" },
    { value: "Asia/Beirut", label: "(UTC+02:00) Beirut" },
    { value: "Asia/Bishkek", label: "(UTC+06:00) Bishkek" },
    { value: "Asia/Brunei", label: "(UTC+08:00) Brunei" },
    { value: "Asia/Chita", label: "(UTC+09:00) Chita" },
    { value: "Asia/Choibalsan", label: "(UTC+08:00) Choibalsan" },
    { value: "Asia/Colombo", label: "(UTC+05:30) Colombo" },
    { value: "Asia/Damascus", label: "(UTC+03:00) Damascus" },
    { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
    { value: "Asia/Dili", label: "(UTC+09:00) Dili" },
    { value: "Asia/Dubai", label: "(UTC+04:00) Dubai" },
    { value: "Asia/Dushanbe", label: "(UTC+05:00) Dushanbe" },
    { value: "Asia/Famagusta", label: "(UTC+02:00) Famagusta" },
    { value: "Asia/Gaza", label: "(UTC+02:00) Gaza" },
    { value: "Asia/Hebron", label: "(UTC+02:00) Hebron" },
    { value: "Asia/Ho_Chi_Minh", label: "(UTC+07:00) Ho Chi Minh" },
    { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong" },
    { value: "Asia/Hovd", label: "(UTC+07:00) Hovd" },
    { value: "Asia/Irkutsk", label: "(UTC+08:00) Irkutsk" },
    { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
    { value: "Asia/Jayapura", label: "(UTC+09:00) Jayapura" },
    { value: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem" },
    { value: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
    { value: "Asia/Kamchatka", label: "(UTC+12:00) Kamchatka" },
    { value: "Asia/Karachi", label: "(UTC+05:00) Karachi" },
    { value: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
    { value: "Asia/Khandyga", label: "(UTC+09:00) Khandyga" },
    { value: "Asia/Kolkata", label: "(UTC+05:30) Kolkata" },
    { value: "Asia/Krasnoyarsk", label: "(UTC+07:00) Krasnoyarsk" },
    { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur" },
    { value: "Asia/Kuching", label: "(UTC+08:00) Kuching" },
    { value: "Asia/Macau", label: "(UTC+08:00) Macau" },
    { value: "Asia/Magadan", label: "(UTC+11:00) Magadan" },
    { value: "Asia/Makassar", label: "(UTC+08:00) Makassar" },
    { value: "Asia/Manila", label: "(UTC+08:00) Manila" },
    { value: "Asia/Nicosia", label: "(UTC+02:00) Nicosia" },
    { value: "Asia/Novokuznetsk", label: "(UTC+07:00) Novokuznetsk" },
    { value: "Asia/Novosibirsk", label: "(UTC+07:00) Novosibirsk" },
    { value: "Asia/Omsk", label: "(UTC+06:00) Omsk" },
    { value: "Asia/Oral", label: "(UTC+05:00) Oral" },
    { value: "Asia/Pontianak", label: "(UTC+07:00) Pontianak" },
    { value: "Asia/Pyongyang", label: "(UTC+09:00) Pyongyang" },
    { value: "Asia/Qatar", label: "(UTC+03:00) Qatar" },
    { value: "Asia/Qostanay", label: "(UTC+05:00) Qostanay" },
    { value: "Asia/Qyzylorda", label: "(UTC+05:00) Qyzylorda" },
    { value: "Asia/Riyadh", label: "(UTC+03:00) Riyadh" },
    { value: "Asia/Sakhalin", label: "(UTC+11:00) Sakhalin" },
    { value: "Asia/Samarkand", label: "(UTC+05:00) Samarkand" },
    { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
    { value: "Asia/Shanghai", label: "(UTC+08:00) Shanghai" },
    { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
    { value: "Asia/Srednekolymsk", label: "(UTC+11:00) Srednekolymsk" },
    { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
    { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
    { value: "Asia/Tbilisi", label: "(UTC+04:00) Tbilisi" },
    { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
    { value: "Asia/Thimphu", label: "(UTC+06:00) Thimphu" },
    { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
    { value: "Asia/Tomsk", label: "(UTC+07:00) Tomsk" },
    { value: "Asia/Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar" },
    { value: "Asia/Urumqi", label: "(UTC+06:00) Urumqi" },
    { value: "Asia/Ust-Nera", label: "(UTC+10:00) Ust-Nera" },
    { value: "Asia/Vladivostok", label: "(UTC+10:00) Vladivostok" },
    { value: "Asia/Yakutsk", label: "(UTC+09:00) Yakutsk" },
    { value: "Asia/Yangon", label: "(UTC+06:30) Yangon" },
    { value: "Asia/Yekaterinburg", label: "(UTC+05:00) Yekaterinburg" },
    { value: "Asia/Yerevan", label: "(UTC+04:00) Yerevan" },
    { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
    { value: "Atlantic/Bermuda", label: "(UTC-04:00) Bermuda" },
    { value: "Atlantic/Canary", label: "(UTC+00:00) Canary" },
    { value: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde" },
    { value: "Atlantic/Faroe", label: "(UTC+00:00) Faroe" },
    { value: "Atlantic/Madeira", label: "(UTC+00:00) Madeira" },
    { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Reykjavik" },
    { value: "Atlantic/South_Georgia", label: "(UTC-02:00) South Georgia" },
    { value: "Atlantic/Stanley", label: "(UTC-03:00) Stanley" },
    { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
    { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane" },
    { value: "Australia/Broken_Hill", label: "(UTC+09:30) Broken Hill" },
    { value: "Australia/Darwin", label: "(UTC+09:30) Darwin" },
    { value: "Australia/Eucla", label: "(UTC+08:45) Eucla" },
    { value: "Australia/Hobart", label: "(UTC+10:00) Hobart" },
    { value: "Australia/Lindeman", label: "(UTC+10:00) Lindeman" },
    { value: "Australia/Lord_Howe", label: "(UTC+10:30) Lord Howe" },
    { value: "Australia/Melbourne", label: "(UTC+10:00) Melbourne" },
    { value: "Australia/Perth", label: "(UTC+08:00) Perth" },
    { value: "Australia/Sydney", label: "(UTC+10:00) Sydney" },
    { value: "Europe/Amsterdam", label: "(UTC+01:00) Amsterdam" },
    { value: "Europe/Andorra", label: "(UTC+01:00) Andorra" },
    { value: "Europe/Astrakhan", label: "(UTC+04:00) Astrakhan" },
    { value: "Europe/Athens", label: "(UTC+02:00) Athens" },
    { value: "Europe/Belgrade", label: "(UTC+01:00) Belgrade" },
    { value: "Europe/Berlin", label: "(UTC+01:00) Berlin" },
    { value: "Europe/Brussels", label: "(UTC+01:00) Brussels" },
    { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest" },
    { value: "Europe/Budapest", label: "(UTC+01:00) Budapest" },
    { value: "Europe/Chisinau", label: "(UTC+02:00) Chisinau" },
    { value: "Europe/Copenhagen", label: "(UTC+01:00) Copenhagen" },
    { value: "Europe/Dublin", label: "(UTC+00:00) Dublin" },
    { value: "Europe/Gibraltar", label: "(UTC+01:00) Gibraltar" },
    { value: "Europe/Helsinki", label: "(UTC+02:00) Helsinki" },
    { value: "Europe/Istanbul", label: "(UTC+03:00) Istanbul" },
    { value: "Europe/Kaliningrad", label: "(UTC+02:00) Kaliningrad" },
    { value: "Europe/Kirov", label: "(UTC+03:00) Kirov" },
    { value: "Europe/Kyiv", label: "(UTC+02:00) Kyiv" },
    { value: "Europe/Lisbon", label: "(UTC+00:00) Lisbon" },
    { value: "Europe/London", label: "(UTC+00:00) London" },
    { value: "Europe/Luxembourg", label: "(UTC+01:00) Luxembourg" },
    { value: "Europe/Madrid", label: "(UTC+01:00) Madrid" },
    { value: "Europe/Malta", label: "(UTC+01:00) Malta" },
    { value: "Europe/Minsk", label: "(UTC+03:00) Minsk" },
    { value: "Europe/Monaco", label: "(UTC+01:00) Monaco" },
    { value: "Europe/Moscow", label: "(UTC+03:00) Moscow" },
    { value: "Europe/Oslo", label: "(UTC+01:00) Oslo" },
    { value: "Europe/Paris", label: "(UTC+01:00) Paris" },
    { value: "Europe/Prague", label: "(UTC+01:00) Prague" },
    { value: "Europe/Riga", label: "(UTC+02:00) Riga" },
    { value: "Europe/Rome", label: "(UTC+01:00) Rome" },
    { value: "Europe/Samara", label: "(UTC+04:00) Samara" },
    { value: "Europe/Saratov", label: "(UTC+04:00) Saratov" },
    { value: "Europe/Simferopol", label: "(UTC+03:00) Simferopol" },
    { value: "Europe/Sofia", label: "(UTC+02:00) Sofia" },
    { value: "Europe/Stockholm", label: "(UTC+01:00) Stockholm" },
    { value: "Europe/Tallinn", label: "(UTC+02:00) Tallinn" },
    { value: "Europe/Tirane", label: "(UTC+01:00) Tirane" },
    { value: "Europe/Ulyanovsk", label: "(UTC+04:00) Ulyanovsk" },
    { value: "Europe/Uzhgorod", label: "(UTC+02:00) Uzhgorod" },
    { value: "Europe/Vienna", label: "(UTC+01:00) Vienna" },
    { value: "Europe/Vilnius", label: "(UTC+02:00) Vilnius" },
    { value: "Europe/Volgograd", label: "(UTC+03:00) Volgograd" },
    { value: "Europe/Warsaw", label: "(UTC+01:00) Warsaw" },
    { value: "Europe/Zaporozhye", label: "(UTC+02:00) Zaporozhye" },
    { value: "Europe/Zurich", label: "(UTC+01:00) Zurich" },
    { value: "Indian/Chagos", label: "(UTC+06:00) Chagos" },
    { value: "Indian/Christmas", label: "(UTC+07:00) Christmas" },
    { value: "Indian/Cocos", label: "(UTC+06:30) Cocos" },
    { value: "Indian/Kerguelen", label: "(UTC+05:00) Kerguelen" },
    { value: "Indian/Mahe", label: "(UTC+04:00) Mahe" },
    { value: "Indian/Maldives", label: "(UTC+05:00) Maldives" },
    { value: "Indian/Mauritius", label: "(UTC+04:00) Mauritius" },
    { value: "Indian/Reunion", label: "(UTC+04:00) Reunion" },
    { value: "Pacific/Apia", label: "(UTC+13:00) Apia" },
    { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland" },
    { value: "Pacific/Bougainville", label: "(UTC+11:00) Bougainville" },
    { value: "Pacific/Chatham", label: "(UTC+12:45) Chatham" },
    { value: "Pacific/Chuuk", label: "(UTC+10:00) Chuuk" },
    { value: "Pacific/Easter", label: "(UTC-06:00) Easter" },
    { value: "Pacific/Efate", label: "(UTC+11:00) Efate" },
    { value: "Pacific/Enderbury", label: "(UTC+13:00) Enderbury" },
    { value: "Pacific/Fakaofo", label: "(UTC+13:00) Fakaofo" },
    { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
    { value: "Pacific/Funafuti", label: "(UTC+12:00) Funafuti" },
    { value: "Pacific/Galapagos", label: "(UTC-06:00) Galapagos" },
    { value: "Pacific/Gambier", label: "(UTC-09:00) Gambier" },
    { value: "Pacific/Guadalcanal", label: "(UTC+11:00) Guadalcanal" },
    { value: "Pacific/Guam", label: "(UTC+10:00) Guam" },
    { value: "Pacific/Honolulu", label: "(UTC-10:00) Honolulu" },
    { value: "Pacific/Kiritimati", label: "(UTC+14:00) Kiritimati" },
    { value: "Pacific/Kosrae", label: "(UTC+11:00) Kosrae" },
    { value: "Pacific/Kwajalein", label: "(UTC+12:00) Kwajalein" },
    { value: "Pacific/Majuro", label: "(UTC+12:00) Majuro" },
    { value: "Pacific/Marquesas", label: "(UTC-09:30) Marquesas" },
    { value: "Pacific/Nauru", label: "(UTC+12:00) Nauru" },
    { value: "Pacific/Niue", label: "(UTC-11:00) Niue" },
    { value: "Pacific/Norfolk", label: "(UTC+11:00) Norfolk" },
    { value: "Pacific/Noumea", label: "(UTC+11:00) Noumea" },
    { value: "Pacific/Pago_Pago", label: "(UTC-11:00) Pago Pago" },
    { value: "Pacific/Palau", label: "(UTC+09:00) Palau" },
    { value: "Pacific/Pitcairn", label: "(UTC-08:00) Pitcairn" },
    { value: "Pacific/Pohnpei", label: "(UTC+11:00) Pohnpei" },
    { value: "Pacific/Port_Moresby", label: "(UTC+10:00) Port Moresby" },
    { value: "Pacific/Rarotonga", label: "(UTC-10:00) Rarotonga" },
    { value: "Pacific/Tahiti", label: "(UTC-10:00) Tahiti" },
    { value: "Pacific/Tarawa", label: "(UTC+12:00) Tarawa" },
    { value: "Pacific/Tongatapu", label: "(UTC+13:00) Tongatapu" },
    { value: "Pacific/Wake", label: "(UTC+12:00) Wake" },
    { value: "Pacific/Wallis", label: "(UTC+12:00) Wallis" },
    { value: "UTC", label: "(UTC+00:00) Coordinated Universal Time" },
];
